//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblDescInvoice
    {
        public int idDescInvoice { get; set; }
        public string idInvoice { get; set; }
        public string productCode { get; set; }
        public int quantity { get; set; }
        public decimal subtotal { get; set; }
    
        public virtual TblInvoice TblInvoice { get; set; }
        public virtual TblProduct TblProduct { get; set; }
    }
}
